// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PinPinServer.Models;

public partial class ChatroomChat
{
    public int Id { get; set; }

    public int ScheduleId { get; set; }

    public int UserId { get; set; }

    public string Message { get; set; }

    public DateTime? CreatedAt { get; set; }

    public bool? IsFocus { get; set; }

    public bool? IsEdited { get; set; }

    public DateTime? LastEditedAt { get; set; }

    public bool? IsDeleted { get; set; }

    public virtual Schedule Schedule { get; set; }

    public virtual User User { get; set; }
}