// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PinPinServer.Models;

public partial class TransportationCategory
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public string Name { get; set; }

    public string Icon { get; set; }

    public virtual ICollection<Transportation> Transportations { get; set; } = new List<Transportation>();

    public virtual User User { get; set; }
}