// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PinPinServer.Models;

public partial class UserFavor
{
    public int Id { get; set; }

    public int? UserId { get; set; }

    public int? FavorCategoryId { get; set; }

    public virtual FavorCategory FavorCategory { get; set; }

    public virtual User User { get; set; }
}