// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PinPinServer.Models;

public partial class User
{
    public int Id { get; set; }

    public string Name { get; set; }

    public DateOnly? Birthday { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string GoogleId { get; set; }

    public string Photo { get; set; }

    public int? Gender { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string PasswordHash { get; set; }

    public int? Role { get; set; }

    public virtual ICollection<ChatroomChat> ChatroomChats { get; set; } = new List<ChatroomChat>();

    public virtual ICollection<ScheduleAuthority> ScheduleAuthorities { get; set; } = new List<ScheduleAuthority>();

    public virtual ICollection<ScheduleDetail> ScheduleDetails { get; set; } = new List<ScheduleDetail>();

    public virtual ICollection<ScheduleGroup> ScheduleGroups { get; set; } = new List<ScheduleGroup>();

    public virtual ICollection<Schedule> Schedules { get; set; } = new List<Schedule>();

    public virtual ICollection<SearchHistory> SearchHistories { get; set; } = new List<SearchHistory>();

    public virtual ICollection<SplitExpenseParticipant> SplitExpenseParticipants { get; set; } = new List<SplitExpenseParticipant>();

    public virtual ICollection<SplitExpense> SplitExpenses { get; set; } = new List<SplitExpense>();

    public virtual ICollection<TransportationCategory> TransportationCategories { get; set; } = new List<TransportationCategory>();

    public virtual ICollection<UserFavor> UserFavors { get; set; } = new List<UserFavor>();

    public virtual ICollection<VoteResult> VoteResults { get; set; } = new List<VoteResult>();

    public virtual ICollection<Vote> Votes { get; set; } = new List<Vote>();

    public virtual ICollection<Wishlist> Wishlists { get; set; } = new List<Wishlist>();
}