// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PinPinServer.Models;

public partial class VoteOption
{
    public int Id { get; set; }

    public int VoteId { get; set; }

    public string Name { get; set; }

    public int? WishlistDetailId { get; set; }

    public virtual Vote Vote { get; set; }

    public virtual ICollection<VoteResult> VoteResults { get; set; } = new List<VoteResult>();

    public virtual WishlistDetail WishlistDetail { get; set; }
}