// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PinPinServer.Models;

public partial class Vote
{
    public int Id { get; set; }

    public int ScheduleId { get; set; }

    public string Name { get; set; }

    public int UserId { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public virtual Schedule Schedule { get; set; }

    public virtual User User { get; set; }

    public virtual ICollection<VoteOption> VoteOptions { get; set; } = new List<VoteOption>();

    public virtual ICollection<VoteResult> VoteResults { get; set; } = new List<VoteResult>();
}